# SPDX-FileCopyrightText: 2024 Dom 'shymega' Rodriguez

# SPDX-License-Identifier: Apache-2.0

[target.x86_64-unknown-linux-musl]
pre-build = [
    "dpkg --add-architecture amd64",
    "apt-get update && apt-get install --assume-yes libssl-dev:amd64"
]
